name: gs_orange
description: Market ready

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+11

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  firebase_auth: ^5.2.0
  firebase_core: ^3.6.0
  firebase_database: ^11.1.1
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.2.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth: ^1.5.3
  desktop_webview_auth: ^0.0.14
  glowy_borders: ^1.0.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  permission_handler: ^11.3.1
  syncfusion_flutter_gauges: ^27.1.56
  app_settings: ^5.1.1
  widgets_easier: ^0.0.10

  bloc: ^8.1.2
  chewie: ^1.7.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  #tryout
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  #tryout
  floor: ^1.4.2
  flutter_bloc: ^8.1.3
  #tryout
  flutter_hooks: ^0.18.3
  equatable: ^2.0.5
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  get_it: ^7.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.2
  #tryout
  intl: ^0.19.0
  lottie: ^2.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.0
  provider: ^6.0.5
  #tryout
  retrofit: ^4.0.3
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  uuid: ^4.1.0
  firebase_analytics: ^11.3.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/cir.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  #the tryout
  retrofit_generator: 8.0.6
  floor_generator: 1.4.2
  build_runner: 2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
